### ISSUE TITLE
Set up project to be able to perform dialyzer and docs mix tasks

### ISSUE THREAD

**Issue by pcmarks** [upstarter/automata#11]
It is desirable to be able to run both the `dialyzer` and `docs` mix tasks after every change to `automata`. They should be run before a PR for a change is requested.

To effect this, `dialyxer` and `ex-doc` needs to be added as dependencies to `mix.ex`

See issues #6, #7 and #9

This should probably be done earlier than later in the project's life. It is my understanding that in a couple of weeks (end of Feb?) there might be some significant changes to `automata` although this should not affect changing  `automata`s dependencies.

Please read the online help for Elixir's dialyzer and docs. tasks.

**Comment by upstarter** [comment]
Thanks @pcmarks, I went ahead and added them. I will add a ticket to make them part of PR's also.
