### ISSUE TITLE
Fix errors/warnings from running `mix dialyzer`. 

### ISSUE THREAD

**Issue by upstarter** [upstarter/automata#19]
If it is too much for one ticket, break it out and create additional issues by module or directory.

**Comment by paultannenbaum** [comment]
I tried picking up this PR as I thought it would be a good way to ramp up on understanding the project and an easy task to help out on, but I was not able to make much headway. 

My first goal was removing all type specs and just getting dialyzer to pass, as I think it is much easier to work from a known passing state and add from there. I was able to get dialyzer to pass if I removed the mock node files, however as soon as something tries to use the `Automation` macro, dialyzer goes haywire. My branch [is here in case](https://github.com/upstarter/automata/tree/dialyzer-passing) it helps.

@upstarter Have you run dialyzer yourself and seen the output? I think there may be some core problems with your existing implementation that are going to keep dialyzer from passing without a somewhat large refactor. I don't understand the project well enough to go down this path at this moment.

**Comment by upstarter** [comment]
I did run dialyzer the other day but did not analyze the results yet. The results were generated to `_build/dev/dialyxir_erlang-22.2.7_elixir-1.10.1_deps-dev.plt`. You just run `mix dialyzer` to view them.  I haven't analyzed them fully, but most just look like missing callbacks and typespec errors like you mentioned. 

I can take a look further when I get a chance, but my best guess right now is that the `import Behavior` for automaton.ex either isn't working right (some metaprogramming  thing) either for the composites or actions. Debugging these things is hard because dialyzer isn't really smart enough to infer things about metaprogramming, but I'm confident we will be able to sort it out in due time.  

Feel free to mess with importing behavior for the nodes, and/or fixing other dialyzers (maybe by file or something). You can also use `.module_info` on the modules in `iex` to check if the behaviors callbacks are being added to the Sequence and/or Action modules.  Hope that helps.

I think I'll focus on testing setup and this for the next week.  Thanks for the help!

**Comment by upstarter** [comment]
Also, the behaviours were pretty hastily put together by me so the callback specifications are likely not at all matching the implementations. Just a heads up. I wanted to get something working quick so people would help out.

**Comment by upstarter** [comment]
Upon further analysis, while I'm a huge believer in merciless refactoring (ala extreme programming), I don't think that a major refactor is needed here. Most of the dialyzer warnings are because the callback specs don't match and other smaller issues, which I did deliberately, knowing I would come back and clean up, which I'm trying to do now.  I'll start with all the behavior callback warnings and testing for that module. If you want to fix/test others that would be great.

**Comment by upstarter** [comment]
STATUS UPDATE: yes I have confirmed that the `Behavior` Behaviour is totally innaccurate and borked up right now as mentioned and fixing things is getting rid of the Dialyzer noise. Fixing as we speak. Should have it cleaned up in a few hours.

**Comment by paultannenbaum** [comment]
Awesome, great to hear. I am happy to help backfill type specs and work on some of the other lo hanging fruit once you get changes branch out. Thanks

**Comment by upstarter** [comment]
Sounds good, I just pushed fixes for most of them. There are currently only 4 dialyzer warnings, most of them tricky due to all the meta-programming (which is normal).  I will do my best to track down solutions.

**Comment by upstarter** [comment]
DEBUGGING NOTE: anytime you see an error or warning that is in one of the mock sequence modules, it probably isn't. It is probably in one of the modules in core that get injected into them. I will put this somewhere in the public project notes.
